### ISSUE TITLE
Backport to 10_6_X code enabling deepTau v2p5

### ISSUE THREAD

**Issue by mbluj** [cms-tau-pog/cmssw#166]
There is an interest to run deepTau v2p5 on top of Run-2 UL samples using CMSSW_10_6_X as this release series is compatible with tools used by groups to analyse Run-2 data. 
The backported code will be used for realistic performance tests and possibly for a real analysis.

Issues with backport of updated code not related to v2p5 (due to evolution between 10_6_X and 12_4_X/12_5_X):
* adaptation to run on both miniAOD and AOD inputs,
* "workaround" fixes,
* code formatting,

... and related to v2p5 (or introduced together with it):
* new scaling infrastructure,
* dropping some inputs to DNN,
* updates and changes in the `runTauIdMVA.py` tool,
* code cleaning (e.g. reduction of usage of `at()` operator).

**Comment by mbluj** [comment]
Testing an initial backport (https://github.com/mbluj/cmssw/tree/CMSSW_10_6_X_deepTau-v2p5) I encountered a problem with TF version mismatch (exception message below [1]) - TF in externals of CMSSW_10_6_30 is v1.6.0, while in externals of 12_4_X/12_5_X it is TF v2.6.x (x=0/6).

@kandrosov, @ofivite: which TF version was used to build graphs of DeepTau v2p5? Is it possible to port the graphs to v1.6.0?

[1] Exception message:
```
error while attaching graph def to session: Not found: Op type not registered 'FusedBatchNormV3' in binary running on PC6BP3. Make sure the Op and Kernel are registered in the binary running in this process.
```

**Comment by kandrosov** [comment]
v2p5 NN was trained and converted to const graph with TF v2.8. We don't use any new layer types compared to  v2p1, so in theory it should be possible to create the const graph which is back compatible with TF 1.6. But this will mean that CMSSW 10_6 distribution will be different wrt master&12_4 or that we will need to replace model in master&12_4... I don't think that we want (and if we will be allowed) to change the version in the master. So I would be more in favour to have a separate distribution for 10_6, but I'm not sure if it is allowed

**Comment by mbluj** [comment]
> v2p5 NN was trained and converted to const graph with TF v2.8. We don't use any new layer types compared to v2p1, so in theory it should be possible to create the const graph which is back compatible with TF 1.6. But this will mean that CMSSW 10_6 distribution will be different wrt master&12_4 or that we will need to replace model in master&12_4... I don't think that we want (and if we will be allowed) to change the version in the master. So I would be more in favour to have a separate distribution for 10_6, but I'm not sure if it is allowed

@kandrosov thank you for answer. I agree with statement that another change of graphs in master&12_4 _X is hardly possible and 10_6_X needs special graphs. However, I think that usage of DeepTau v2p5 with 10_6_X should be generally considered only as a "Tau POG" solution for realistic performance tests, i.e. within a real analysis setup, and for run-2 data analyses which are ongoing or about to start. For analyses with a longer time line (e.g. combining run-2 and run-3 data) I think one will use releases >=12_4_X. So I think we should try to provide a private branch of RecoTauTag/TriningFiles containing DeepTau v2p5 graphs converted to TF 1.6 (or earlier) and only those graphs to be used with 10_6_X. When the graphs are ready I can test them against current ones with 12_4/12_5_X and 10_6_X.

What can be a timescale to convert such TF 1.6 compatible graphs?

**Comment by shedprog** [comment]
@mbluj unfortunately we give up attempts to have TF 1 compatible backports... after fixing the error on the step of graph loading (listed above) there were errors on the execution step stating that TF version should exactly correspond to 1.6. After rolling back our model building code to the older version of api and loading model by weights we compiled tf==1.6.0 graph, but tests showed that this model is not compatible with v2p5...

Here is the plots with the scores and deltas:
![image](https://user-images.githubusercontent.com/31743376/180417162-bb53e166-ed28-4bd3-bb02-833cad760249.png)
![image](https://user-images.githubusercontent.com/31743376/180417272-cebf8e41-0e6b-453d-9285-fab127a18e38.png)
![image](https://user-images.githubusercontent.com/31743376/180417353-4c543808-b5a2-408c-84fb-ad746758a18b.png)
![image](https://user-images.githubusercontent.com/31743376/180417422-2826523b-b5a2-4b14-ae6a-23c99e593a00.png)
![image](https://user-images.githubusercontent.com/31743376/180417469-93f4bf20-6814-462b-af92-23187880f081.png)
![image](https://user-images.githubusercontent.com/31743376/180417522-e02d14f5-21a7-4caa-aaff-cd47d390595e.png)

**Comment by mbluj** [comment]
Do you think that conversion of v2p5 graphs to any TF 1.X version is possible? 
Generally, what can be a plan for v2p5 with 10_6_X? Surely one can run v2p5 with 12_5_X on top of UL samples, but it was disfavored option.

**Comment by kandrosov** [comment]
Unfortunatelly the situation with backcompatibility TF 2->1 is way worst that I've originaly thought. At this point, we only have an option to start a very low level debugging, which would require considerable investment of person-power and success is not guaranteed. 

I propose that we abandon this effort and go to the plan B: v2p5 will be available for releases 12_4 or above and we provide instruction how to run nano v9-like production with 12_4 for UL analyses. And if some groups are using private framework, they would need to adapt their code for 12_4.

**Comment by mbluj** [comment]
I am closing this issue.
Production of NanoAOD v9 or newer with new releases on top of UL samples works well.
